#!/bin/sh
# Builds a small program that links the MeshRepair backend installed into a
# Bambu Studio source tree with Bambu Studio's own MeshDiagnostics, then runs
# it on the given meshes (STL / OBJ / 3MF).
#
#   ./install.py /path/to/BambuStudio
#   ./verify/verify.sh /path/to/BambuStudio broken1.stl broken2.3mf ...
#
# Needs a C++17 compiler and the Boost.Log and TBB development packages
# (Arch: boost tbb, Debian/Ubuntu: libboost-log-dev libtbb-dev,
#  Fedora: boost-devel tbb-devel).
set -e
if [ $# -lt 2 ]; then
    echo "usage: $0 /path/to/BambuStudio mesh [mesh ...]" >&2
    exit 1
fi
BAMBU=$(cd "$1" && pwd)
shift
HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../../.." && pwd)
OUT="${TMPDIR:-/tmp}/meshrepair-bambu-verify"
if [ ! -f "$BAMBU/src/libslic3r/MeshRepairFix.cpp" ]; then
    echo "error: run install.py on $BAMBU first" >&2
    exit 1
fi
# libslic3r_version.h is normally generated by Bambu Studio's CMake.
GEN="$OUT.include"
mkdir -p "$GEN"
sed -e 's/@BBL_RELEASE_TO_PUBLIC@/1/' -e 's/@BBL_INTERNAL_TESTING@/0/' -e 's/@[A-Z_]*@/verify/' \
    "$BAMBU/src/libslic3r/libslic3r_version.h.in" > "$GEN/libslic3r_version.h"
${CXX:-c++} -std=c++17 -O2 -DHAS_MESHREPAIR -DHAS_MODEL_REPAIR -DBOOST_LOG_DYN_LINK -I"$GEN" \
    -I"$BAMBU/src" -I"$BAMBU/src/libslic3r" -I"$BAMBU/src/eigen" -I"$BAMBU/src/libigl" \
    -I"$REPO/libmeshrepair/include" -include "$BAMBU/src/libslic3r/Point.hpp" \
    "$HERE/harness.cpp" "$BAMBU/src/libslic3r/MeshRepairFix.cpp" \
    "$BAMBU/src/libslic3r/MeshDiagnostics.cpp" "$BAMBU/src/libslic3r/MeshRaycast.cpp" \
    "$REPO"/libmeshrepair/src/*.cpp \
    -o "$OUT" -lboost_log -lboost_thread -ltbb -lpthread
exec "$OUT" "$@"
